### ISSUE TITLE
Performance increase with RTOS?

### ISSUE THREAD

**Issue by cmb87** [ETH-PBL/NanoSLAM#1]
Hello there,
first of all congratulations for this fantastic project. This is very inspiring! From a first glimpse into gap9-app it looks like the system is not taking advantage of a RTOS? Do I see it correctly? Could this be maybe another performance speed up for your algorithm?

**Comment by ETH-PBL** [comment]
GAP9 SDK supports FreeRTOS. The code released here is meant to be general and implementable on different application scenario such as general purpose MCUs. Therefore, it is released as bare-metal implementation. RTOS will surely help the integration of our NanoSLAM with other parallel tasks.
